// netlify/functions/getInfo.js
exports.handler = async (event, context) => {
  const data = {
    files: [
      "main.2bad9164.css",
      "main.d94e7b82.js",
      "index.html",
      "asset-manifest.json",
      "favicon.ico",
      "manifest.json",
      "robots.txt"
    ],
    directories: [
      "static",
      "css",
      "js",
      "android-chrome-192x192 - Copy.png",
      "apple-touch-icon - Copy.png",
      "apple-touch-icon.png"
    ]
  };

  return {
    statusCode: 200,
    body: JSON.stringify(data),
  };
};
